disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - function_body_length
  - function_parameter_count
  - identifier_name
  - file_length
  - type_body_length
  - large_tuple
  - legacy_random

excluded:
  - .build
  - .git
  - .github
